### ISSUE TITLE
[ILM] ILM configuration overwrite

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/beats#11594]
I have detected that the ILM configuration is overwritten many times without modification by a user.

<img width="1217" alt="Screenshot 2019-04-02 at 11 52 58" src="https://user-images.githubusercontent.com/5400788/55394283-3e6ad480-553f-11e9-900b-f034c6ea14d8.png">

<img width="1184" alt="Screenshot 2019-04-02 at 11 55 49" src="https://user-images.githubusercontent.com/5400788/55394278-3b6fe400-553f-11e9-8e18-bad315704166.png">

For confirmed bugs, please report:
- Version: 7.0.0-rc1, 7.0.0-rc2
- Operating System: Linus on k8s
- Steps to Reproduce: 

* Starts a k8s cluster with Metricbeat and Packetbeat as daemonset, with the following output configuration

```
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      index: "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"
      ssl.enabled: true
      ssl.verification_mode: none
    xpack.monitoring.enabled: true
    setup.kibana.host: ${KIBANA_PROTO}://${KIBANA_HOST}:${KIBANA_PORT:5601}
    setup.kibana.username: ${KIBANA_USERNAME}
    setup.kibana.password: ${KIBANA_PASSWORD}
    setup.template.name: "metricbeat"
    setup.template.pattern: "metricbeat-*"
    setup.template.enabled: true
    setup.template.overwrite: true
```

```
    setup.template.overwrite: true
    xpack.monitoring.enabled: true
    queue.mem:
      events: 20000
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      index: "packetbeat-%{[agent.version]}-%{+yyyy.MM.dd}"
      ssl.enabled: true
      ssl.verification_mode: none
      bulk_max_size: 2000
      worker: 2
      compression_level: 5
    xpack.monitoring.enabled: true
    setup.kibana.host: ${KIBANA_PROTO}://${KIBANA_HOST}:${KIBANA_PORT:5601}
    setup.kibana.username: ${KIBANA_USERNAME}
    setup.kibana.password: ${KIBANA_PASSWORD}
    setup.template.name: "packetbeat"
    setup.template.pattern: "packetbeat-*"
    setup.template.enabled: true
    setup.template.overwrite: true
```

**Comment by urso** [comment]
This was a bug in the release candidates. It should be fixed in the final 7.0.0 release.

**Comment by kuisathaverat** [comment]
@urso on 7.0.0 works as expected, but on 8.0.0-SNAPSHOT the issue is still there and Packetbeat overwrites the ILM configuration, Metricbeat works correctly on both versions.

**Comment by kuisathaverat** [comment]
Filebeat has the same issue

**Comment by Tsuweiquan** [comment]
Winlogbeat 7.0.1 has the same issue. 

`setup.ilm.overwrite: false`  overwrites the existing ilm policy.
