### ISSUE TITLE
Outdated API version in the Metricbeat Azure module Billing set

### ISSUE THREAD

**Issue by toby-sutor** [elastic/beats#20758]
It seems like we are referencing an outdated API version in the (Beta) [Azure module / Billing metricset](https://www.elastic.co/guide/en/beats/metricbeat/7.9/metricbeat-metricset-azure-billing.html) for Metricbeat.

E.g. in https://github.com/elastic/beats/blob/496e3c9a066120ef23a8a5efd12fe970c5a49a19/x-pack/metricbeat/module/azure/billing/client.go#L13 

https://github.com/elastic/beats/blob/496e3c9a066120ef23a8a5efd12fe970c5a49a19/x-pack/metricbeat/module/azure/billing/service.go#L10

https://github.com/elastic/beats/blob/496e3c9a066120ef23a8a5efd12fe970c5a49a19/x-pack/metricbeat/module/azure/billing/data.go#L12

we’re referring to API version `2019-01-01` but in the [Microsoft docs](https://docs.microsoft.com/en-us/rest/api/consumption/usagedetails/list) the API version is `2019-10-01`.

This leads to error: 
```
INFO module/wrapper.go:259 Error fetching data for metricset azure.billing: error retrieving usage information: 
Retrieving usage details failed in client: consumption.UsageDetailsClient#List: Failure responding to request:
StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="400" 
Message="Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01
```

**Comment by narph** [comment]
@toby-sutor ,
I am not able to reproduce this issue and I can retrieve the data fine.
Also we cannot update until the azure sdk will offer us the new version https://github.com/Azure/azure-sdk-for-go/tree/master/services/consumption/mgmt (we would find an workaround in case there are critical issues).
The error could also tell us that the subscription might not have the rights to access the data. 
These APIs currently only support Enterprise Enrollments and Web Direct Subscriptions (with a few exceptions), can you tell us what is the type of subscription you have currently configured?

**Comment by narph** [comment]
I have created an issue for mapping the `2019-10-01` consumption API's inside the sdk https://github.com/Azure/azure-sdk-for-go/issues/12452. 
The latest version seems to support more subscription types than the ones mentioned above.

**Comment by toby-sutor** [comment]
As discussed offline, from what I found at https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/consumption-api-overview and more specifically here: https://docs.microsoft.com/en-us/partner-center/azure-plan-available it appears that there is no API access available for CSP subscriptions, which has been the case here. Hence the error message we receive is misleading.

**Comment by narph** [comment]
reopening this, the new version 2019-10-01 seems to not support filtering by the usage dates.

**Comment by willemdh** [comment]
Please fix this...

**Comment by willemdh** [comment]
When will this get some attention..? This module hasn't worked at all for many months now. You can as well just delete it...

**Comment by kasper112** [comment]
I still have the same problem any news here ?

**Comment by MohammadBangee** [comment]
Has this issue been resolved because I am still facing this issue.

error retrieving usage information: Retrieving usage details failed in client: consumption.UsageDetailsClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="400" Message="Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01

**Comment by MohammadBangee** [comment]
> thanks all for your patience with this
> 
> we are now actively working on this - we will update progress here when we have a more concrete timeline for shipping the fix

Dear @tommyers-elastic 
Has this issue been resolved?
I am still facing this issue on MetricBeat and Elastic Agent.

**Comment by DougBellinger** [comment]
We are also experiencing this with elastic 7.17 in the cloud

**Comment by udaydaayam** [comment]
we are experiencing as well.
11:07:24.136
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] Error fetching data for metricset azure.billing: error retrieving usage information: Retrieving usage details failed in client: consumption.UsageDetailsClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="400" Message="Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01 (Request ID: 0277fbdc-23db-48ce-80e9-bccb982c0814)"

**Comment by zmoog** [comment]
Hey @MohammadBangee @DougBellinger 

We fixed this issue by upgrading Usage Details API in Beats to version 2019-10-01.

Here's the availability of the fix across releases:

- 8.4: included in 8.4.0 due for a public release later in August.
- 8.3: included in [8.3.3](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-8.3.3.html) available today.
- 7.17: targeting 7.17.6 due in mid September.

**Comment by zmoog** [comment]
@udaydaayam, which version of Beats are you currently using?

**Comment by willemdh** [comment]
Hello @tommyers-elastic ,

We just updated to 7.17.7 and it appears this issue is still not fixed.. When the billing metricset is configured, the following error is logged on metricbeat start:

`Nov 02 13:59:29 myhostname metricbeat[8884]: ERROR module/wrapper.go:259 Error fetching data for metricset azure.billing: error retrieving usage information: Retrieving usage details failed in client: consumption.UsageDetailsClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="400" Message="Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01 (Request ID: 0ae2ddfe-aeb6-4be4-949f-a3e2dae3de47)"`

This has been broken for so long.....

**Comment by willemdh** [comment]
Really sorry to hear that we spent 2 days upgrading our pr cluster because this thread mentioned it was going to be fixed in 7.16....

**Comment by zmoog** [comment]
I am so sorry to hear this. I feel your pain. My apologies for not providing you with more timely updates and precise wording [^1]. 

Let me try to help you with the next steps.

To discover what's released, you can reference the Beats release notes. For 7.17.x, you can check https://www.elastic.co/guide/en/beats/libbeat/7.17/release-notes.html and check if we included the expected change in a release. In the release notes, you can look for the PR number or the description [CHANGELOG.next.asciidoc](https://github.com/elastic/beats/pull/32297/files#diff-867eb8a32d99eda9bb244b7b86d7abd0031618bae71d0276fe139fe697c3063d) file. 

Please contact me if you need any help or have questions. I'll do my best to assist you.

[^1]: I used the word "targeting 7.17.6" because until we merge the fix in the branch, we are not sure it can hit that version.
