### ISSUE TITLE
[Ingest Manager] When running the Elastic-Agent uninstall.ps1 file, it does not remove Endpoint, if running

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#20895]
[Ingest Manager] When running the Elastic-Agent uninstall.ps1 file, it does not remove Endpoint, if running
 - this is Windows only.  But we should make sure that any solution coming in the future and the .deb / .rpm Linux package usage do the same.

- Steps to Reproduce: 
Install Agent on Windows per documentation, and use the ps1 script
Add 'Endpoint' to the Agent policy / config
Run the ps1 'uninstaller' script and note that Endpoint is left running

**Comment by nfritts** [comment]
Reported by users here: https://discuss.elastic.co/t/uninstall-install-elastic-endpoint-endpoint-stays-after-uninstall/247014

**Comment by EricDavisX** [comment]
@rahulgupta-qasource can you re-test this usage / scenario in master line?  it should be fixed with latest refactor.

**Comment by blakerouse** [comment]
@EricDavisX this is not fixed, only way still to remove Elastic Endpoint is to remove the integration from Fleet, then uninstall Elastic Agent.

**Comment by EricDavisX** [comment]
Blake - yes, that's exactly what I meant.  We do not intend to use the .ps1 file at all, and I know its being removed - so we can update test scenarios, automation and expectations around this.  I appreciate the note
