### ISSUE TITLE
Support Beats on Oracle Linux with UEK

### ISSUE THREAD

**Issue by sherry-ger** [elastic/beats#21777]
**Describe the enhancement:**

It appears both Filebeat and Metricbeat work on Oracle Linux with UEK.  Please officially support Beats on Oracle Linux with UEK.

**Describe a specific use case for the enhancement or feature:**

The use case here is to support Beats on Oracle Linux with UEK.

**Comment by 111andre111** [comment]
This is for sure supposed to be open.

**Comment by jlind23** [comment]
@111andre111 it should be solved by https://github.com/elastic/e2e-testing/pull/2208 right?
Should be good in 8.2.
cc @nimarezainia

**Comment by 111andre111** [comment]
@jlind23 Unfortunately this particular PR doesn't solve UEK of Oracle Linux as far as I understand.
By default on Oracle Linux you don't have UEK kernel.
UEK = Unbreakable Enterprise Kernel
You install the kernel by:
`yum install kernel-uek`

**Comment by jlind23** [comment]
@111andre111 thanks for the update, @nimarezainia could you please take a look at this one and see how we should proceed?
cc @cmacknz @pierrehilbert
