### ISSUE TITLE
[Agent] macOS or Linux Agent will show as unhealthy / error state if 'Windows' Integration is in policy used

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#23996]
7.11.0 shipped Beta build

From Security team:
noticed that the Endpoint/Fleet behavior changed with regards to integrations. 

In 7.10 I made a single policy for all of the hosts and just put the Linux, Windows, and Mac endpoints under that Policy. In 7.11 my Mac hosts are always in an error state because the Windows integration won’t load.

Work-around is to use separate policy for each OS variant.

error in Agent logs:
[elastic_agent][error] 2021-02-11T07:45:45-05:00: type: 'ERROR': sub_type: 'FAILED' message: Application: filebeat--7.11.0[47c935b0-6bba-11eb-b89f-d98cec7202ae]: State changed to FAILED: 1 error: 5 errors: Error creating runner from config: failed in processor.javascript: GoError: Could not load module 'windows': cannot load windows, only built-in modules are supported; Error creating runner from config: failed in processor.javascript: GoError: Could not load module 'windows': cannot load windows, only built-in modules are supported; Error creating runner from config: failed in processor.javascript: GoError: Could not load module 'windows': cannot load windows, only built-in modules are supported; Error creating runner from config: failed in processor.javascript: GoError: Could not load module 'windows': cannot load windows, only built-in modules are supported; Error creating runner from config: failed in processor.javascript: GoError: Could not load module 'windows': cannot load windows, only built-in modules are supported

![Screen Shot 2021-02-11 at 7 47 09 AM](https://user-images.githubusercontent.com/12970373/107638337-6f3cea00-6c3d-11eb-92aa-6976052d5ab0.png)

**Comment by ph** [comment]
This is indeed a problem with the integration javascript pipeline. @masci

**Comment by EricDavisX** [comment]
The .0.10.7 System package is seen in 7.11 shipped release, and 0.2.11 Windows Package shows.  System Package should have the desired conditional logic, but Windows may not.  Suggest to review what conditional logic we have there.  I missed testing this; we were over focused on the intended behaviors and not about the unintended / non-happy paths.  We are in the middle of a test cycle for the 0.9.3 System package which is tied to 7.10.x and upgrade problems with 7.11 - this may be the same need for testing (back on 7.10.x).

**Comment by fearful-symmetry** [comment]
@EricDavisX is right--we're missing a lot of conditional logic from non-system packages, since I was so focused on getting `system` to work.

**Comment by ph** [comment]
OK, I was totally confused, I've mismatched the windows integration vs the system integration.

**Comment by EricDavisX** [comment]
confirmed it happens with Linux as well as macOS agents

**Comment by fearful-symmetry** [comment]
Fix has been merged in integrations. Going to try and roll things out today.

**Comment by EricDavisX** [comment]
we confirmed these 2 updates are on 'staging' now and can be tested via 7.11.x cloud-staging -snapshot deploy:
"linux" integration to version 0.3.7
"windows" to version 0.3.1

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have re-validated this issue on 7.11.1 snapshot build and found issue still occurring, however, with metricbeat error this time on MAC Agent. 

Build details are as follows:
```
BUILD 37947
COMMIT b8ce8c202dff437413cdd01d5ba956bfa41bb8af
Artifact link used: https://artifacts-api.elastic.co/v1/search/7.11.1-SNAPSHOT
```

**Observations :**
- Updated integration versions were getting displayed.
"Linux" integration Version 0.3.7
"windows" Version 0.3.1

However, System package was still at V 0.10.8 an not as 0.10.9.
![image](https://user-images.githubusercontent.com/72375798/108168888-00b8ca00-711e-11eb-98ed-d1cb70fbfe25.png)

Further, when deployed different OSs agent  to default policy having all the above mentioned integrations[System, windows and Linux], we observed that after almost an hour, 
- MacOS and Linux OS Agent goes to unhealthy state.
- metricbeat errors were logged in MAC Agent's Log UI.
![image](https://user-images.githubusercontent.com/72375798/108169947-71141b00-711f-11eb-8e68-73ed67add023.png)


**Error Logs generated under MAC Agent:**
```
11:31:38.743
elastic_agent
[elastic_agent][error] 2021-02-17T01:01:37-05:00: type: 'ERROR': sub_type: 'FAILED' message: Application: metricbeat--7.11.1-SNAPSHOT[9ec87830-70e2-11eb-a85f-af7706749f88]: State changed to FAILED: 1 error: 5 errors: Error creating runner from config: 1 error: metricset 'system/entropy' not found; Error creating runner from config: 1 error: could not read /proc: stat /proc: no such file or directory; Error creating runner from config: 1 error: metricset 'system/socket' not found; Error creating runner from config: 1 error: metricset 'system/users' not found; Error creating runner from config: 1 error: error connecting to dbus: dial unix /run/systemd/private: connect: no such file or directory
```
Then, again on navigating back to agents, after another one hour we observed that Linux agent resumes its state back to Healthy. Please find complete Agent logs from Kibana UI in below attachment.

[MAC_Agent_KibanaUILogs.txt](https://github.com/elastic/beats/files/5993954/MAC_Agent_KibanaUILogs.txt)
[Linux_Agent_KibanaUILogs.txt](https://github.com/elastic/beats/files/5993956/Linux_Agent_KibanaUILogs.txt)

**Note:** No Filebeat/Metricbeat errors were noticed for Linux Agent.

Please let us know if anything else is required from our side.

Thanks
QAS

**Comment by EricDavisX** [comment]
@amolnater-qasource @dikshachauhan-qasource Per the above PR we are promoting fixes and they will be rolled out to staging so they can easily be re-validated.  Please open a new ticket if / when you find anything further.  

Thanks Alex!
