### ISSUE TITLE
Flaky Tests: TestFilestream, TestDefaultHarvester

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#26727]
I spotted some flakiness today around filestreams:

```
Stacktrace
=== RUN   TestFilestreamCloseRenamed
coverage: 60.1% of statements
panic: test timed out after 10m0s
goroutine 56 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1700 +0xe5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x45
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0004b6900, 0xcf31f5, 0x1a, 0xd19158, 0x493d01)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000583380)
	/usr/local/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000583380, 0xc00063fda8)
	/usr/local/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc00000f050, 0x12f60c0, 0x32, 0x32, 0xc030e5b7ef618972, 0x8bb495756a, 0x1318600, 0xce993f)
	/usr/local/go/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc000514380, 0x0)
	/usr/local/go/src/testing/testing.go:1417 +0x1eb
```

```
=== RUN   TestDefaultHarvesterGroup/assert_a_harvester_for_same_source_cannot_be_started
coverage: 40.0% of statements
panic: test timed out after 10m0s
goroutine 9 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1700 +0xe5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x45
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0005abc80, 0xcdcc4c, 0x19, 0xcfdd50, 0x493101)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000483380)
	/usr/local/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000483380, 0xc00025fda8)
	/usr/local/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc0004c6a08, 0x1249b00, 0x11, 0x11, 0xc030e5b82b0d4b9d, 0x8bb49cbf0e, 0x1257c80, 0xcd4a8f)
	/usr/local/go/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc0004f4300, 0x0)
	/usr/local/go/src/testing/testing.go:1417 +0x1eb
main.main()
	_testmain.go:141 +0x1c5
goroutine 53 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0005c8180, 0xcef827, 0x34, 0xc00059b4b0, 0xd9d401)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup(0xc0005abc80)
	/go/src/github.com/elastic/beats/filebeat/input/filestream/internal/input-logfile/harvester_test.go:155 +0x18a
testing.tRunner(0xc0005abc80, 0xcfdd50)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3
goroutine 57 [sleep]:
time.Sleep(0x989680)
	/usr/local/go/src/runtime/time.go:193 +0xd2
github.com/elastic/beats/v7/libbeat/tests/resources.(*GoroutinesChecker).WaitUntilIncreased(0xc00006ae28, 0x2)
	/go/src/github.com/elastic/beats/libbeat/tests/resources/goroutines.go:95 +0x2c
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup.func5(0xc0005c8180)
```

```
=== RUN   TestDefaultHarvesterGroup/assert_a_harvester_for_same_source_cannot_be_started
coverage: 40.0% of statements
panic: test timed out after 10m0s
goroutine 9 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1700 +0xe5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x45
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0005abc80, 0xcdcc4c, 0x19, 0xcfdd50, 0x493101)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000483380)
	/usr/local/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000483380, 0xc00025fda8)
	/usr/local/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc0004c6a08, 0x1249b00, 0x11, 0x11, 0xc030e5b82b0d4b9d, 0x8bb49cbf0e, 0x1257c80, 0xcd4a8f)
	/usr/local/go/src/testing/testing.go:1509 +0x2fe
```

```
Failed
Stacktrace
=== RUN   TestDefaultHarvesterGroup/assert_a_harvester_is_started_in_a_goroutine
```

Links:
https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/master/890/tests/

**Comment by cmacknz** [comment]
Fixed as part of https://github.com/elastic/beats/issues/31517

**Comment by faec** [comment]
`TestDefaultHarvesterGroup` still failing on windows when reenabled at head https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-34856/6/#showFailuresLink:

```
[Build&Test / filebeat-unitTest / github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup/assert_already_locked_resource_has_no_problem_when_harvestergroup_is_cancelled](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-34856/6/testReport/junit/github/com_elastic_beats_v7_filebeat_input_filestream_internal_input-logfile/Build_Test___filebeat_unitTest___TestDefaultHarvesterGroup_assert_already_locked_resource_has_no_problem_when_harvestergroup_is_cancelled/)
[Build&Test / filebeat-unitTest / github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-34856/6/testReport/junit/github/com_elastic_beats_v7_filebeat_input_filestream_internal_input-logfile/Build_Test___filebeat_unitTest___TestDefaultHarvesterGroup/)
[Build&Test / filebeat-windows-2016-windows-2016 / github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup/assert_already_locked_resource_has_no_problem_when_harvestergroup_is_cancelled](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-34856/6/testReport/junit/github/com_elastic_beats_v7_filebeat_input_filestream_internal_input-logfile/Build_Test___filebeat_windows_2016_windows_2016___TestDefaultHarvesterGroup_assert_already_locked_resource_has_no_problem_when_harvestergroup_is_cancelled/)
[Build&Test / filebeat-windows-2016-windows-2016 / github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-34856/6/testReport/junit/github/com_elastic_beats_v7_filebeat_input_filestream_internal_input-logfile/Build_Test___filebeat_windows_2016_windows_2016___TestDefaultHarvesterGroup/)
[Build&Test / filebeat-windows-2022-windows-2022 / github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup/assert_already_locked_resource_has_no_problem_when_harvestergroup_is_cancelled](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-34856/6/testReport/junit/github/com_elastic_beats_v7_filebeat_input_filestream_internal_input-logfile/Build_Test___filebeat_windows_2022_windows_2022___TestDefaultHarvesterGroup_assert_already_locked_resource_has_no_problem_when_harvestergroup_is_cancelled/)
[Build&Test / filebeat-windows-2022-windows-2022 / github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-34856/6/testReport/junit/github/com_elastic_beats_v7_filebeat_input_filestream_internal_input-logfile/Build_Test___filebeat_windows_2022_windows_2022___TestDefaultHarvesterGroup/)
[Build&Test / filebeat-goIntegTest / github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup/assert_already_locked_resource_has_no_problem_when_harvestergroup_is_cancelled](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-34856/6/testReport/junit/github/com_elastic_beats_v7_filebeat_input_filestream_internal_input-logfile/Build_Test___filebeat_goIntegTest___TestDefaultHarvesterGroup_assert_already_locked_resource_has_no_problem_when_harvestergroup_is_cancelled/)
[Build&Test / filebeat-goIntegTest / github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-34856/6/testReport/junit/github/com_elastic_beats_v7_filebeat_input_filestream_internal_input-logfile/Build_Test___filebeat_goIntegTest___TestDefaultHarvesterGroup/)
```
