### ISSUE TITLE
[cloud] Elastic Agent upgrade from 7.12.2-SNAPSHOT to 7.15.2-SNAPSHOT fails

### ISSUE THREAD

**Issue by simitt** [elastic/beats#28719]
When upgrading from a stack version that was only running APM Server `7.12.2-SNAPSHOT` to `7.15.2-SNAPSHOT` the Elastic Cloud agent policy was not set up properly. The Elastic Agent and Fleet Server are not running as expected, in my case there was no Fleet Server policy added to the cloud agent policy. When upgrading to `7.16.0-SNAPSHOT` , the elastic-agent and fleet-server process where not successful.

The issue was originally reported by @dasansol92 when using Build Candidates for trying to upgrade from `7.12` to `7.15` to `7.16`, the upgrade to `7.16` completely failed. 

**Steps to reproduce**
1. Create deployment with APM enabled in `7.12`
2. Upgrade to `7.15` 
3. Check eastic agent logs showing errors, and Elastic Agent Cloud policy does not contain Fleet Server
4. Upgrade to `7.16` and check elastic agent logs and if fleet-server endpoint is up

**Comment by nchaulet** [comment]
> We have a PR that wasn't backported to 7.15.2 that may contain the fix for this issue. @nchaulet are we able to test the upgrade path w/ this PR included, or do we need to backport and test against snapshot?

elastic/kibana#115030

I Tested the backport locally and looks like it solving the bug so I am going to backport it to 7.15

**Comment by dasansol92** [comment]
Hey @nchaulet , I see the same on my end

**Comment by nchaulet** [comment]
> Hey @nchaulet , I see the same on my end

This should be solved by https://github.com/elastic/kibana/pull/116998

**Comment by nchaulet** [comment]
Just tested the upgrade from 7.12 SNAPSHOT to 7.15.2 to 7.16 everything is now working.

**Comment by dasansol92** [comment]
@nchaulet I'm still having issues with missing stream templates in cloud when upgrading from 7.15.1 to 7.16.0.
I started this deployment in 7.12.0 and then I upgraded it to 7.14.0->7.15.1->7.16.0

![Screenshot 2021-11-09 at 12 28 11](https://user-images.githubusercontent.com/15727784/140916223-9c37dbce-6fe3-4f0b-a7fb-7e2e7ee85b4f.png)

Deployment: https://admin.staging.foundit.no/deployments/88da4ea13c844a0bb30fe5379ab28a07

**Comment by nchaulet** [comment]
@dasansol92 Yes I got the same bug trying to confirming the bug is fixed we came with a new solution https://github.com/elastic/kibana/pull/117594

**Comment by nchaulet** [comment]
Tested and https://github.com/elastic/kibana/pull/117594 fixed the bug

**Comment by dasansol92** [comment]
Hi @nchaulet, this is still happening to me. I just did a 7.12 deployment and applied the following upgrades:
- 7.12 -> 7.14 -> 7.15.1 -> 7.16

And the result is an unhealthy apm/fleet instance with this logs in kibana:

![Screenshot 2021-11-19 at 11 20 39](https://user-images.githubusercontent.com/15727784/142606743-0aa75b72-e6b8-4cd9-8877-00270f580188.png)


Deployment ID: `8b153fe8ef2f4df28219d490d0b27475`
