### ISSUE TITLE
Filebeat's Kibana module doesn't support new 8.0 logging format

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#31216]
For confirmed bugs, please report:
- Version: Kibana 8.0+
- Operating System: n/a
- Discuss Forum URL: n/a
- Steps to Reproduce: 

Starting with v8.0, Kibana introduces a [new logging system](https://www.elastic.co/guide/en/kibana/master/logging-config-changes.html) that changes the JSON fields that are generated.

The `kibana` module doesn't support the new fields: expects a `pid` field, while the new format outputs ECS-compatible `process.pid`. Other fields need review.

This results in an ingestion:
> "error.message": "field [kibana.log.meta.pid] doesn't exist"

**Comment by insukcho** [comment]
Do we have any workarounds before fixing the bug?

**Comment by klacabane** [comment]
@insukcho Ignoring failures of the `kibana.log.meta.pid` processor would allow the documents to be processed further down the pipeline. I'm still ramping up on the kibana logs to filebeat ingestion so I can't tell yet if any other processor will fail with the new format


<img width="706" alt="Screenshot 2022-04-13 at 12 07 24" src="https://user-images.githubusercontent.com/5239883/163155888-0f9f6418-a231-4072-a18f-b082a141ee40.png">

**Comment by klacabane** [comment]
Raised a potential bug in Kibana log entries https://github.com/elastic/kibana/issues/130118

**Comment by klacabane** [comment]
Fix was merged in main and backported to 8.2

**Comment by BLKingLLC** [comment]
I'm still seeing this in 8.2, but this time it appears to be only occurring on Machine Learning entries.

@klacabane  should this be a new issue or a recurrence of this same issue?


![Screenshot from 2022-05-16 12-12-26](https://user-images.githubusercontent.com/6933081/168637333-c9e331f1-30b1-4864-915e-0d46b707f72f.png)

**Comment by klacabane** [comment]
Hi @muratkucuktepe, is this happening in cloud or onprem environment ? Which filebeat/kibana version are you using ? The `kibana.log` pipeline was reworked in 8.8 (https://github.com/elastic/beats/pull/35268), are you able to test this version to see if it fixes the issue ?

**Comment by klacabane** [comment]
@muratkucuktepe The filebeat version running in production does not fully support 8.0+ log format and should be upgraded. I've reproduced the issue and using a filebeat > v8.2 fixes it. You can use 8.5.3 to align with the production stack
