### ISSUE TITLE
Heartbeat screenshot not working

### ISSUE THREAD

**Issue by b2ronn** [elastic/beats#33822]
I'm trying to deploy a heartbeat through an elastic-agent+fleet in an openshift cluster.

from docs - https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html
```Replace docker.elastic.co/beats/elastic-agent with docker.elastic.co/beats/elastic-agent-complete and use the elastic-agent user instead of root to run Synthetics Browser tests. Synthetics tests cannot run under the root user. Refer to [Synthetics Fleet Quickstart](https://www.elastic.co/guide/en/observability/8.5/uptime-set-up.html) for more information.```

not as root, I can't change folders - /usr/local/share/ca-certificates/ and /etc/ssl/certs
ok, adding them as empty-dir

```apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: agent-heartbeat
spec:
  deployment:
    podTemplate:
      metadata:
        creationTimestamp: null
      spec:
        automountServiceAccountToken: true
        containers:
          - image: 'docker.elastic.co/beats/elastic-agent-complete:8.4.3'
            name: agent
            resources:
              limits:
                cpu: '2'
                memory: 4Gi
              requests:
                cpu: 50m
                memory: 1Gi
            volumeMounts:
              - mountPath: /usr/local/share/ca-certificates/
                name: usr-ca-certificates
              - mountPath: /etc/ssl/certs
                name: etc-ssl-certs
        securityContext:
          runAsUser: 1000
        serviceAccountName: epm-paas-apm-elasticagent
        volumes:
          - emptyDir: {}
            name: agent-data
          - emptyDir: {}
            name: usr-ca-certificates
          - emptyDir: {}
            name: etc-ssl-certs
    replicas: 1
    strategy: {}
  fleetServerRef:
    name: fleetserver
  kibanaRef:
    name: kibana
  mode: fleet
  policyID: heartbeat-agent
  serviceAccountName: elasticagent
  version: 8.4.3
```

added script
```
step("homepage", async () => {
  await page.goto('https://google.com', { waitUntil: 'networkidle' });
});
```
![image](https://user-images.githubusercontent.com/20790707/204060397-a59b720a-6000-4001-8cdd-55983ec8b2a4.png)

and there is no screenshot in result in kibana
![image](https://user-images.githubusercontent.com/20790707/204060444-835cc281-d27c-4947-a1da-2c8b64f2f9a7.png)

ps: 
eck 2.4.0
openshift 4.11
addwd anyuid for serviceaccount - oc adm policy add-scc-to-user anyuid -z elasticagent  -n elastic

**Comment by emilioalvap** [comment]
Hi @b2ronn,

We are aware of some issues with screenshots that have been fixed in `8.4` and `8.5`, I believe this issue falls under that category. Screenshots are working on the latest available release.

**Comment by b2ronn** [comment]
updated to 
 - eck to  2.5.0
 - elastic/kibana/elastic-agents to 8.5.2

but still can't see screenshots in kibana.

**Comment by shahzad31** [comment]
@b2ronn if you go to discover do you see any data for following index in synthetics data 

`synthetics.type : "screenshot/block" 
`
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/3505601/204570570-8ad34f42-3143-4cfd-9d8d-a034ee609da2.png">

**Comment by b2ronn** [comment]
from dataview (synthetics-data-view)*,heartbeat-8*,heartbeat-7*,synthetics-* i see only such types.

![image](https://user-images.githubusercontent.com/20790707/204640063-3f76ff80-d600-4759-8a1f-ec4f9997c92f.png)

**Comment by b2ronn** [comment]
I removed all tests. Removed integrations. restarted the container with the agent. added tests. Screenshots appeared.
but there is no location in kibana now.
![image](https://user-images.githubusercontent.com/20790707/204653157-93a16a69-187a-4528-94d4-949e1d996d79.png)
```
"package": {
      "name": "@elastic/synthetics",
      "version": "1.0.0-beta.37"
    },
```

**Comment by dominiqueclarke** [comment]
The lack of a location name is on us, and I've raised https://github.com/elastic/integrations/issues/4735 to track.

**Comment by paulb-elastic** [comment]
@b2ronn I'm going to close this as you've got screenshots working now.

As @dominiqueclarke mentioned, https://github.com/elastic/integrations/issues/4735 fixes the location name problem.  Please refer to [these details](https://github.com/elastic/integrations/issues/4735#issuecomment-1335789195) on how to make the locations appear with this fix.
