### ISSUE TITLE
Packetbeat flows enhancements

### ISSUE THREAD

**Issue by urso** [elastic/beats#3444]
Flows support in 5.0 is quite rudimentary, not really taking any network layers (arbitrary timeout) into account and only counting packets and bytes. Plus, there is a parent-child relation between flows and transactions, not yet represented in packetbeat events being published.

List of flow proposed enhancements:

- [ ] pass active flow to packet analyzer:
  - [ ] add protocol specific stats to flows (e.g. number of transactions with success/failure/dropped due to packet loss/timed out)
  - [ ] add flow id to protocol transaction events to establish some relationship between flows and transaction
- [ ] add support to tie flow lifetime to connection status:
  - [ ] Flows for TCP/SCTP streams do not timeout while TCP connection is active
  - [ ] Protocols on top of UDP managing connection state should be able to disable flow timeout
  - [ ] Stop flow if connection is closed or connection attempt failed:
    - [ ] for TCP stop flow on RST or normal TCP shutdown
    - [ ] consider ICMP messages if TCP/UDP port is not reachable
    - [ ] timeout flow in case of handshake being incomplete and no data being send in either direction
  - [ ] add indicator (string?) to indicate the reason a flow has ended
  - [ ] add indicator if connection has been good (established TCP connection), in case it ended forcefully
  - [ ] add indicator for flow starting to capture an older TCP connection (not having seen the connection attempt itself, as packetbeat was started after)
- [ ] report TCP level stats:
  - [ ] count flags usage (SYN, RST, FIN, PUSH)
  - [ ] report bytes lost due to packet-loss
  - [ ] report packets fully/partially resend (number of packets and bytes)

**Comment by tbragin** [comment]
@urso @adriansr Does this pull close or partially address this issue? https://github.com/elastic/beats/pull/5476

**Comment by urso** [comment]
@tbragin No. Flows support and integrating flows into application protocols is about collecting metrics only.

**Comment by london2016** [comment]
If using Packetbeat and not interested in any of the supported protocols can we have a generic "TCP" option where can specifiy a list of ports to be able to follow traffic flows

**Comment by urso** [comment]
@london2016 this can already be done by configuring your custom packet filter in the device configs. Please checkout [the forums](https://discuss.elastic.co/c/beats/packetbeat) if you need any help.

**Comment by q2dg** [comment]
Well...version 7.0 is here and nothing has been resolved about this issue yet...

**Comment by Umarhayat3** [comment]
PB version 7.3.1 has been released but this issue is still there and many are facing problems due to lack of information in debugging mode. This flow enhancement is necessary for troubleshooting.

**Comment by faec** [comment]
Adding this to triage because we're still seeing requests for ways to measure tcp connection drops in particular and it looks like this fell off the radar for a while.

**Comment by zez3** [comment]
would be a nice addition

**Comment by zez3** [comment]
Part of the proposed enhancements would still be useful to have.
@jamiehynds 
Would it be possible to take some enhancements on the roadmap?

**Comment by wangxin688** [comment]
It would be a very nice feature to support translation layer for TCP/UDP, which will help measure network performance, especially for forwording devices(use linux as a gateway, running routing, NAT, and firewall function)

**Comment by willemdh** [comment]
.

**Comment by gaby** [comment]
This issue still work in progress after 7 years?

**Comment by pierrehilbert** [comment]
@nfritts is your team planning to work on this or should we close this issue to avoid users to have false expectations?
